backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "/src/posts"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", wdiget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
  - name: "people"
    label: "People"
    folder: "/src/_data/people.json"
    fields:
    - {label: "Name", name: "name", widget: "string"}
    - {label: "Age", name: "age", widget: "number"}
    